<?php

return [
    '1' => [
        'model' => 'Honda Click',
        'type' => 'moto',
        'engine' => 150,
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2020-2022',
        'fuel' => 'Бензин А95',
        'consumption' => '4л/100км',
        'seats' => '2',
        'image' => 'click.png',
        'multimedia' => 'USB',
        'price' => 5,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '7/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '2' => [
        'model' => 'Honda PCX',
        'type' => 'moto',
        'engine' => 150,
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2018-2021',
        'fuel' => 'Бензин А95',
        'consumption' => '4л/100км',
        'seats' => '2',
        'image' => 'pcx.png',
        'multimedia' => 'USB',
        'price' => 6,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],


    '3' => [
        'model' => 'Honda ADV',
        'type' => 'moto',
        'engine' => 150,
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2018-2021',
        'fuel' => 'Бензин А95',
        'consumption' => '4л/100км',
        'seats' => '2',
        'image' => 'adblack.png',
        'multimedia' => 'USB',
        'price' => 7,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    

    '4' => [
        'model' => 'Honda Forza',
        'type' => 'moto',
        'engine' => 300,
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2018-2021',
        'fuel' => 'Бензин А95',
        'consumption' => '4л/100км',
        'seats' => '2',
        'image' => '11.png',
        'multimedia' => 'USB',
        'price' => 10,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '5' => [
        'model' => 'Yamaha XMAX',
        'type' => 'moto',
        'engine' => 300,
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2018-2021',
        'fuel' => 'Бензин A95',
        'consumption' => '4л/100км',
        'seats' => '2',
        'image' => '12.png',
        'multimedia' => 'USB',
        'price' => 10,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '6' => [
        'model' => 'Yamaha TMAX',
        'type' => 'bike',
        'engine' => 300,
        'transmission' => 'AКПП',
        'ac' => 1,
        'year' => '2020',
        'fuel' => 'Бензин A95',
        'consumption' => '3л/100км',
        'seats' => '2',
        'image' => '13.png',
        'multimedia' => 'USB',
        'price' => 27,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-03-13 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    '7' => [
        'model' => 'Honda Rebel 500',
        'type' => 'moto',
        'engine' => 500,
        'transmission1' => 'РКПП',
        'ac' => 1,
        'year' => '2022',
        'fuel' => 'Бензин А95',
        'consumption' => '4л/100км',
        'seats' => '2',
        'image' => 'rebel_500.png',
        'multimedia' => 'USB',
        'price' => 25,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '8' => [
        'model' => 'Honda CB500X',
        'type' => 'moto',
        'engine' => 500,
        'transmission1' => 'РКПП',
        'ac' => 1,
        'year' => '2022',
        'fuel' => 'Бензин А95',
        'consumption' => '4л/100км',
        'seats' => '2',
        'image' => 'cb500x.png',
        'multimedia' => 'USB',
        'price' => 25,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
];
