<?php

return [
    '1' => [
        'model' => 'Lagoon 420 (pretty alien)',
        'type' => 'yaht',
        'engine' => '2x40 cc',
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Дизель',
        'consumption' => '10л/100миль',
        'seats' => '2',
        'toilet' => '2',
        'snork' => 'Рыбалка + Снорклинг',
        'image' => '1.jpg',
        'multimedia' => 'BT, AUX',
        'price' => 370,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '2' => [
        'model' => 'Fountaine Pajot Bahia46',
        'type' => 'yaht',
        'engine' => '2x40 cc',
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Дизель',
        'consumption' => '10л/100миль',
        'seats' => '2',
        'toilet' => '2',
        'snork' => 'Рыбалка + Снорклинг',
        'image' => '2.jpg',
        'multimedia' => 'BT, AUX',
        'price' => 470,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '3' => [
        'model' => 'Pajot Marquise56',
        'type' => 'yaht',
        'engine' => '2x40 cc',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Дизель',
        'consumption' => '10л/100миль',
        'seats' => '2',
        'toilet' => '2',
        'snork' => 'Снорклинг + рыбалка',
        'image' => '3.jpg',
        'multimedia' => 'BT, AUX',
        'price' => 570,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-03-13 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
];
