<?php

return [
    '1' => [
        'model' => 'Toyota Yaris Ativ ',
        'type' => 'sedan',
        'engine' => '1.2',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => '2021',
        'fuel' => 'Бензин A91',
        'consumption' => '6л/100км',
        'seats' => 'Пять',
        'image' => 'toyota_yaris_ativ.png',
        'multimedia' => 'USB | AUX | *Bluetooth',
        'price' => 20,
        'deposit' => 150,
        'discount' => 20,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '2' => [
        'model' => 'Mazda 2 ',
        'type' => 'sedan',
        'engine' => '1.2',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Бензин A91',
        'consumption' => '6л/100км',
        'seats' => 'Пять',
        'image' => 'mazda2.png',
        'multimedia' => 'USB | AUX | *Bluetooth',
        'price' => 21,
        'deposit' => 150,
        'discount' => 20,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '3' => [
        'model' => 'Toyota Yaris Ativ',
        'type' => 'sedan',
        'engine' => '1.2',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Бензин A91',
        'consumption' => '6л/100км',
        'seats' => 'Пять',
        'image' => 'ativ_new.png',
        'multimedia' => 'USB | AUX | *Bluetooth',
        'price' => 20,
        'deposit' => 150,
        'discount' => 20,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '4' => [
        'model' => 'Toyota Vios',
        'type' => 'sedan',
        'engine' => '1.5',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Бензин A91',
        'consumption' => '7л/100км',
        'seats' => 'Пять',
        'image' => 'toyota_vios.png',
        'multimedia' => 'USB | AUX',
        'price' => 20,
        'deposit' => 150,
        'discount' => 15,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '5' => [
        'model' => 'Honda City',
        'type' => 'sedan',
        'engine' => '1.5',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => '2022',
        'fuel' => 'Бензин A91',
        'consumption' => '7л/100км',
        'seats' => 'Пять',
        'image' => 'hondas.png',
        'multimedia' => 'USB | AUX',
        'price' => 21,
        'deposit' => 150,
        'discount' => 15,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '6' => [
        'model' => 'Toyota Altis',
        'type' => 'sedan',
        'engine' => '1.6',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => '2022',
        'fuel' => 'Бензин A95',
        'consumption' => '8л/100км',
        'seats' => 'Пять',
        'image' => 'altis.png',
        'multimedia' => 'USB | AUX | Bluetooth',
        'price' => 23,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-03-13 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '7' => [
        'model' => 'Toyota Camry',
        'type' => 'sedan',
        'engine' => '2.5',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => '2022',
        'fuel' => 'Бензин A95',
        'consumption' => '8л/100км',
        'seats' => 'Пять',
        'image' => 'camry.png',
        'multimedia' => 'USB | AUX | Bluetooth',
        'price' => 40,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-03-13 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '8' => [
        'model' => 'Toyota Veloz',
        'type' => 'miniwan',
        'engine' => '1.5',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Бензин A91',
        'consumption' => '8л/100км',
        'seats' => 'Семь',
        'image' => 'veloz.png',
        'multimedia' => 'USB | AUX',
        'price' => 35,
        'deposit' => 150,
        'discount' => 10,
        'rating' => '7/10',
        'available' => ['start' => '2020-03-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '10' => [
        'model' => 'Toyota Fortuner',
        'type' => 'jeep',
        'engine' => '2.8',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Дизель',
        'consumption' => '10л/100км',
        'seats' => 'Семь',
        'image' => 'toyota_fortuner.png',
        'multimedia' => 'USB | AUX | Bluetooth',
        'price' => 42,
        'deposit' => 400,
        'discount' => 10,
        'rating' => '9/10',
        'available' => ['start' => '2020-01-01 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '11' => [
        'model' => 'Toyota Cross',
        'type' => 'miniven',
        'engine' => '2.0',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Бензин A95',
        'consumption' => '8л/100км',
        'seats' => 'Пять',
        'image' => 'cross.png',
        'multimedia' => 'USB | AUX',
        'price' => 35,
        'deposit' => 400,
        'discount' => 10,
        'rating' => '7/10',
        'available' => ['start' => '2020-03-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '12' => [
        'model' => 'MG ZS',
        'type' => 'miniwan',
        'engine' => '2.0',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Бензин A95',
        'consumption' => '8л/100км',
        'seats' => 'Пять',
        'image' => 'mg.png',
        'multimedia' => 'USB | AUX',
        'price' => 25,
        'deposit' => 400,
        'discount' => 10,
        'rating' => '7/10',
        'available' => ['start' => '2020-03-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '13' => [
        'model' => 'Hyundai H1 VIP',
        'type' => 'miniven',
        'engine' => 2.5,
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Дизель',
        'consumption' => '10л/100км',
        'seats' => 'Семь',
        'image' => 'hundai_h1.png',
        'multimedia' => 'USB | AUX | Bluetooth',
        'price' => 60,
        'deposit' => 400,
        'discount' => 10,
        'rating' => '9/10',
        'available' => ['start' => '2020-01-01 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '14' => [
        'model' => 'Ford Ranger',
        'type' => 'jeep',
        'engine' => 2.8,
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Дизель',
        'consumption' => '10л/100км',
        'seats' => 'Пять',
        'image' => 'ranger.png',
        'multimedia' => 'USB | AUX | Bluetooth',
        'price' => 43,
        'deposit' => 400,
        'discount' => 10,
        'rating' => '9/10',
        'available' => ['start' => '2020-01-01 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '15' => [
        'model' => 'Ford Everest',
        'type' => 'jeep',
        'engine' => 2.2,
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Дизель',
        'consumption' => '10л/100км',
        'seats' => 'Семь',
        'image' => 'ford_everest.png',
        'multimedia' => 'USB | AUX | *Bluetooth',
        'price' => 42,
        'deposit' => 400,
        'discount' => 10,
        'rating' => '7/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '16' => [
        'model' => 'Mitsubishi Padgero',
        'type' => 'jeep',
        'engine' => 2.8,
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Дизель',
        'consumption' => '10л/100км',
        'seats' => 'Семь',
        'image' => 'padgero.png',
        'multimedia' => 'USB | AUX | *Bluetooth',
        'price' => 42,
        'deposit' => 400,
        'discount' => 10,
        'rating' => '7/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '17' => [
        'model' => 'Mitsubishi X-Pander',
        'type' => 'hachbag',
        'engine' => '1.5',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Дизель',
        'consumption' => '10л/100км',
        'seats' => 'Семь',
        'image' => 'xpander.png',
        'multimedia' => 'USB | AUX | *Bluetooth',
        'price' => 32,
        'deposit' => 400,
        'discount' => 10,
        'rating' => '7/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '18' => [
        'model' => 'BMW X1',
        'type' => 'hachbag',
        'engine' => '2.0',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Дизель',
        'consumption' => '10л/100км',
        'seats' => 'Пять',
        'image' => 'x1.png',
        'multimedia' => 'USB | AUX | *Bluetooth',
        'price' => 250,
        'deposit' => 1000,
        'discount' => 10,
        'rating' => '7/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '19' => [
        'model' => 'BMW X5',
        'type' => 'hachbag',
        'engine' => '2.0',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Дизель',
        'consumption' => '10л/100км',
        'seats' => 'Пять',
        'image' => 'x5.png',
        'multimedia' => 'USB | AUX | *Bluetooth',
        'price' => 500,
        'deposit' => 2000,
        'discount' => 10,
        'rating' => '7/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '20' => [
        'model' => 'BMW 320GT',
        'type' => 'liftback',
        'engine' => '2.0',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => ' Дизель',
        'consumption' => '7л/100км',
        'seats' => 'Пять',
        'image' => 'bmw_320_gt.png',
        'multimedia' => 'USB | AUX | Bluetooth',
        'price' => 155,
        'deposit' => 1000,
        'discount' => 10,
        'rating' => '10/10',
        'available' => ['start' => '2021-02-21 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '21' => [
        'model' => 'Mersedes CLA',
        'type' => 'sedan',
        'engine' => '2.5',
        'transmission' => 'auto',
        'ac' => 1,
        'year' => 2022,
        'fuel' => 'Бензин А95',
        'consumption' => '8л/100км',
        'seats' => 'Пять',
        'image' => 'mercedes_cla.png',
        'multimedia' => 'USB | AUX | Bluetooth',
        'price' => 155,
        'deposit' => 1000,
        'discount' => 10,
        'rating' => '10/10',
        'available' => ['start' => '2020-03-27 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
];
