<?php

return [
    '1' => [
        'model' => 'Острова Raya и Coral',
        'type' => 'moto',
        'engine' => '1 день',
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Фрукты и напитки',
        'consumption' => '8 часов',
        'seats' => '20',
        'image' => 'coral.jpg',
        'multimedia' => 'Русский гид',
        'price' => 45,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '2' => [
        'model' => 'Симиланы',
        'type' => 'moto',
        'engine' => '1 день',
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Фрукты и напитки',
        'consumption' => '8 часов',
        'seats' => '20',
        'image' => 'similany.jpg',
        'multimedia' => 'Русский гид',
        'price' => 50,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '3' => [
        'model' => '11 Островов',
        'type' => 'moto',
        'engine' => '1 день',
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Фрукты и напитки',
        'consumption' => '8 часов',
        'seats' => '20',
        'image' => '11islands.jpg',
        'multimedia' => 'Русский гид',
        'price' => 55,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '4' => [
        'model' => 'Остров Phi-Phi',
        'type' => 'moto',
        'engine' => '1 день',
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Фрукты и напитки',
        'consumption' => '8 часов',
        'seats' => '20',
        'image' => 'phi.jpg',
        'multimedia' => 'Русский гид',
        'price' => 43,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '5' => [
        'model' => 'Остров Джеймса Бонда',
        'type' => 'moto',
        'engine' => '1 день',
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Фрукты и напитки',
        'consumption' => '8 часов',
        'seats' => '20',
        'image' => 'bond1.jpg',
        'multimedia' => 'Русский гид',
        'price' => 43,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
    
    '6' => [
        'model' => 'Bamboo Rafting',
        'type' => 'moto',
        'engine' => '1 день',
        'transmission1' => 'АКПП',
        'ac' => 1,
        'year' => '2023',
        'fuel' => 'Фрукты и напитки',
        'consumption' => '8 часов',
        'seats' => '20',
        'image' => 'bamboo.jpg',
        'multimedia' => 'Русский гид',
        'price' => 44,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '8/10',
        'available' => ['start' => '2020-01-28 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
];
