<?php

return [
    '1' => [
        'model' => 'Любые типы виз',
        'type' => 'visa',
        'engine' => '1 год',
        'transmission' => 'Обучение в школе',
        'ac' => 1,
        'year' => '2021-2022',
        'fuel' => 'Бензин А95',
        'consumption' => '',
        'seats' => 'Виза на 1 год',
        'image' => '1.jpg',
        'multimedia' => 'Английский, Тайский',
        'price' => 1,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '5/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],

    '2' => [
        'model' => 'Thailand Elite Card',
        'type' => 'visa',
        'engine' => 'до 20 лет',
        'transmission' => 'Elite Card',
        'ac' => 1,
        'year' => '2021-20**',
        'fuel' => 'VIP Членство',
        'consumption' => '',
        'seats' => 'Виза от 5 лет',
        'multimedia' => 'Английский, Тайский',
        'image' => '2.jpg',
        'price' => 3,
        'deposit' => 0,
        'discount' => 10,
        'rating' => '5/10',
        'available' => ['start' => '2020-12-25 10:00', 'end' => '2029-12-28 10:00'],
        'tabs' => [],
    ],
];
